---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "iqs-bundles-support-node"
  description: "Microservice for deploying support pip-services microservices"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

  # Performance counters that posts values to log
- descriptor: "pip-services:counters:log:default:1.0"
  level: "trace"

# AWS logging component
- descriptor: "pip-services:logger:cloudwatch:default:1.0"
  level: "info"
  group: "{{ENV_NAME}}"
  connection:
    region: "{{{AWS_REGION}}}"
  credential:
    access_id: "{{{AWS_ACCESS_ID}}}"
    access_key: "{{{AWS_ACCESS_KEY}}}"

# AWS metrics component
- descriptor: "pip-services:counters:cloudwatch:default:1.0"
  level: "info"
  connection:
    region: "{{{AWS_REGION}}}"
  credential:
    access_id: "{{{AWS_ACCESS_ID}}}"
    access_key: "{{{AWS_ACCESS_KEY}}}"

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: "http"
    host: "0.0.0.0"
    port: 8080

# Heartbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

# Discovery service
- descriptor: "pip-services:discovery:memory:default:*"
  mongodb: "uri={{{MONGO_SERVICE_URI}}};host={{{MONGO_SERVICE_HOST}}};port={{{MONGO_SERVICE_PORT}}};database={{{MONGO_DB}}}"

############## SupportBundle components ##############

# Feedbacks components
- descriptor: "pip-services-feedbacks:persistence:mongodb:default:*"
  connection:
    discovery_key: mongodb
- descriptor: "pip-services-feedbacks:controller:default:default:*"
- descriptor: "pip-services-feedbacks:client:direct:default:*"
- descriptor: "pip-services-feedbacks:service:http:default:*"

# Announcements components
- descriptor: "pip-services-announcements:persistence:mongodb:default:*"
  connection:
    discovery_key: mongodb
- descriptor: "pip-services-announcements:controller:default:default:*"
- descriptor: "pip-services-announcements:client:direct:default:*"
- descriptor: "pip-services-announcements:service:http:default:*"
